/**
 * Copyright (c) 2026 hangtiancheng
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { render } from "preact";
import { LocationProvider, Router, Route } from "preact-iso";
import {
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DocsLayout,
  DocsProvider,
  Input,
  cn,
  decryptContent,
} from "@swifty.js/docs";
// Auto-generated by defineConfig()
import {
  docsConfig,
  loadContent,
  getSearchIndex,
} from "@swifty-docs/generated";

// CSS
import "./main.css";
import { Lock, X } from "lucide-preact";
import { useCallback, useEffect, useRef, useState } from "preact/compat";

type PageModule = { pageData: any; contentHtml: string };

const DENIED_HTML = `
<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:45vh;gap:1rem;text-align:center;font-family:inherit;">
  <svg width="52" height="52" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" style="opacity:0.35">
    <rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/><circle cx="12" cy="16" r="1"/>
  </svg>
  <div>
    <p style="font-size:1.15rem;font-weight:700;margin:0 0 0.4rem;">Access Denied</p>
    <p style="font-size:0.85rem;opacity:0.55;margin:0;">This page is password-protected. Enter the correct password to view its content.</p>
  </div>
</div>`;

let askUnlockFn: ((payload: any) => Promise<string | null>) | null = null;

function parsePayload(html: string) {
  try {
    const obj = JSON.parse(html);
    if (obj && typeof obj.encrypted === "string" && obj.salt && obj.iv)
      return obj;
  } catch {}
  return null;
}

async function guardedLoadContent(path: string): Promise<PageModule | null> {
  const mod = await loadContent(path);
  if (!mod) return null;

  const payload = parsePayload(mod.contentHtml);
  if (!payload) return mod;

  const cached = sessionStorage.getItem("docs-guard-pwd");
  if (cached) {
    try {
      const html = await decryptContent(payload, cached);
      return { ...mod, contentHtml: html };
    } catch {
      sessionStorage.removeItem("docs-guard-pwd");
    }
  }

  const html = await askUnlockFn!(payload);
  if (html === null) return { ...mod, contentHtml: DENIED_HTML };
  return { ...mod, contentHtml: html };
}

function shakeElement(el: HTMLElement) {
  el.animate(
    [
      { transform: "translateX(0)" },
      { transform: "translateX(-6px)" },
      { transform: "translateX(5px)" },
      { transform: "translateX(-4px)" },
      { transform: "translateX(3px)" },
      { transform: "translateX(0)" },
    ],
    { duration: 400, easing: "ease-in-out" },
  );
}

function PasswordDialog({
  payload,
  onUnlock,
  onClose,
}: {
  payload: any;
  onUnlock: (html: string, pwd: string) => void;
  onClose: () => void;
}) {
  const [value, setValue] = useState("");
  const [error, setError] = useState("");
  const [checking, setChecking] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const cardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const handleSubmit = useCallback(
    async (e: Event) => {
      e.preventDefault();
      if (!value.trim() || checking) return;
      setChecking(true);
      try {
        const html = await decryptContent(payload, value);
        onUnlock(html, value);
      } catch {
        setError("Incorrect password. Please try again.");
        if (cardRef.current) shakeElement(cardRef.current);
        setChecking(false);
        inputRef.current?.select();
      }
    },
    [value, checking, payload, onUnlock],
  );

  return (
    <Dialog open onOpenChange={(open) => !open && onClose()}>
      <DialogPortal>
        <DialogOverlay class="z-999 backdrop-blur-[6px]" />
        <div class="fixed inset-0 z-999 grid place-items-center p-4">
          <DialogContent class="w-full max-w-sm p-8" ref={cardRef}>
            <form onSubmit={handleSubmit} class="flex flex-col">
              <button
                type="button"
                aria-label="Close"
                onClick={onClose}
                class="text-muted-foreground hover:bg-muted absolute top-3 right-3 flex h-7 w-7 items-center justify-center rounded-md opacity-60 transition-all duration-150 hover:opacity-100"
              >
                <X size={15} />
              </button>

              <div class="border-border bg-accent text-primary mb-5 flex h-12 w-12 items-center justify-center rounded-lg border">
                <Lock size={24} strokeWidth={1.5} />
              </div>

              <DialogTitle class="text-[1.05rem] font-bold tracking-tight">
                Password Required
              </DialogTitle>
              <DialogDescription class="text-muted-foreground mt-1 mb-5 text-[0.82rem]">
                This page is protected. Enter the password to view its content.
              </DialogDescription>

              <Input
                ref={inputRef}
                type="password"
                value={value}
                onInput={(e) => {
                  setValue((e.target as HTMLInputElement).value);
                  setError("");
                }}
                placeholder="Password"
                class={cn(
                  "h-auto py-2.5",
                  error && "border-destructive focus-visible:border-destructive",
                )}
              />
              {error && (
                <p class="text-destructive mt-2 text-[0.78rem] font-medium">
                  {error}
                </p>
              )}

              <Button
                type="submit"
                disabled={checking}
                class="mt-5 w-full font-semibold"
              >
                {checking ? "Verifying..." : "Unlock"}
              </Button>
            </form>
          </DialogContent>
        </div>
      </DialogPortal>
    </Dialog>
  );
}

function App() {
  const [dialog, setDialog] = useState<{ payload: any } | null>(null);
  const resolveRef = useRef<((html: string | null) => void) | null>(null);

  askUnlockFn = useCallback((payload: any): Promise<string | null> => {
    return new Promise((resolve) => {
      resolveRef.current = resolve;
      setDialog({ payload });
    });
  }, []);

  const handleUnlock = useCallback((html: string, pwd: string) => {
    sessionStorage.setItem("docs-guard-pwd", pwd);
    setDialog(null);
    resolveRef.current?.(html);
    resolveRef.current = null;
  }, []);

  const handleClose = useCallback(() => {
    setDialog(null);
    resolveRef.current?.(null);
    resolveRef.current = null;
  }, []);

  return (
    <>
      {dialog && (
        <PasswordDialog
          payload={dialog.payload}
          onUnlock={handleUnlock}
          onClose={handleClose}
        />
      )}
      <DocsProvider
        config={docsConfig}
        loadContent={guardedLoadContent}
        getSearchIndex={getSearchIndex}
      >
        <LocationProvider>
          <Router>
            <Route path="/" component={DocsLayout} />
            <Route default component={DocsLayout} />
          </Router>
        </LocationProvider>
      </DocsProvider>
    </>
  );
}

render(<App />, document.getElementById("app")!);
