import { render } from "preact";
import { LocationProvider, Router, Route } from "preact-iso";
import { DocsLayout, DocsProvider } from "@swifty.js/docs";

// Auto-generated by defineConfig()
import {
  docsConfig,
  loadContent,
  getSearchIndex,
} from "@swifty-docs/generated";

// CSS
import "./main.css";

render(
  <DocsProvider
    config={docsConfig}
    loadContent={loadContent}
    getSearchIndex={getSearchIndex}
  >
    <LocationProvider>
      <Router>
        <Route path="/" component={DocsLayout} />
        <Route default component={DocsLayout} />
      </Router>
    </LocationProvider>
  </DocsProvider>,
  document.getElementById("app")!,
);
