/**
 * Type-safe configuration helper with automatic route generation.
 *
 * Scans the docs directory, generates sidebar/search index, and writes
 * a routes module to `.lark-docs/generated/` so that `boot.ts` can
 * import routes and site data via the `@lark-docs/generated` alias.
 *
 * Usage:
 * ```ts
 * import { defineConfig } from "@lark.js/docs";
 *
 * export default defineConfig({
 *   docs: "docs",
 *   baseUrl: "/docs/",
 *   title: "My Library",
 * });
 * ```
 *
 * The optional second argument `projectRoot` controls path resolution
 * for the `docs` directory and the generated output. Defaults to
 * `process.cwd()`, which is the project root in most Vite/Webpack/Rspack
 * setups.
 */
import type { DocsConfig, SidebarConfig } from "./types";
import { scanDocsDir } from "./scanner";
import { generateRouteMap } from "./route-map";
import { generateSidebar } from "./sidebar-generator";
import { buildSearchIndex } from "./search-index";
import { isAbsolute, resolve } from "node:path";
import { mkdirSync, writeFileSync } from "node:fs";

export function defineConfig(
  config: DocsConfig,
  projectRoot: string = process.cwd(),
): DocsConfig {
  generateRoutesFile(config, projectRoot);
  return config;
}

/**
 * Generate a physical routes module into `{projectRoot}/.lark-docs/generated/`.
 *
 * This file is regenerated each time the config is loaded (dev or build).
 * It imports all .md files (compiled by the bundler plugin), registers each
 * as a View class, and exports the route map + site data for boot.ts.
 *
 * Written to `.lark-docs/` (a dot directory at project root, similar to
 * `.vitepress/` or `.docusaurus/`) so it can be gitignored and inspected
 * directly. Consumers import it via a Vite resolve alias `@lark-docs/generated`.
 */
function generateRoutesFile(config: DocsConfig, projectRoot: string): void {
  const docsDir = isAbsolute(config.docs)
    ? config.docs
    : resolve(projectRoot, config.docs);

  const routes = scanDocsDir(docsDir, config.baseUrl);
  const routeMap = generateRouteMap(routes);

  // Build sidebar
  const sidebar: Record<string, SidebarConfig> = {};
  if (config.sidebar) {
    for (const [prefix, sidebarConfig] of Object.entries(config.sidebar)) {
      if (sidebarConfig === "auto") {
        sidebar[prefix] = generateSidebar(routes, prefix, config.baseUrl);
      } else {
        sidebar[prefix] = sidebarConfig;
      }
    }
  }

  // Build search index (skip when provider is "none")
  const searchIndex =
    config.search?.provider === "none" ? [] : buildSearchIndex(routes);

  // Generate import statements for each .md file.
  // Use absolute paths so the generated module works from .lark-docs/.
  const generatedDir = resolve(projectRoot, ".lark-docs/generated");
  const imports = routes
    .map(
      (r, i) =>
        `// @ts-ignore
      import view${i} from ${JSON.stringify(r.filePath)};`,
    )
    .join("\n");

  // Generate registerViewClass calls
  const registrations = routes
    .map((r, i) => `registerViewClass(${JSON.stringify(r.viewId)}, view${i});`)
    .join("\n");

  // Compose runtime docsConfig (includes build-time searchIndex,
  // which is not part of the user-facing DocsConfig type)
  const runtimeConfig = {
    title: config.title,
    description: config.description || "",
    lang: config.lang || "en-US",
    nav: config.nav || [],
    sidebar,
    searchIndex,
  };

  const fileContent = `// Auto-generated by defineConfig() — DO NOT EDIT!!!
// Generated at: ${new Date().toISOString()}

import { registerViewClass } from "@lark.js/mvc";

${imports}

${registrations}

export const routes: Record<string, string> = ${JSON.stringify(routeMap, null, 2)};

export const docsConfig = ${JSON.stringify(runtimeConfig, null, 2)};
`;

  // Write generated module to .lark-docs/generated/
  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(resolve(generatedDir, "index.ts"), fileContent, "utf-8");
}
