/**
 * Type-safe configuration helper with automatic route generation.
 *
 * Scans the docs directory, generates sidebar/search index, and writes
 * a routes module to `.lark-docs/generated/` so that `boot.ts` can
 * import routes and site data via the `@lark-docs/generated` alias.
 *
 * Usage:
 * ```ts
 * import { defineConfig } from "@lark.js/docs";
 *
 * export default defineConfig({
 *   docs: "docs",
 *   baseUrl: "/docs/",
 *   title: "My Library",
 * });
 * ```
 *
 * The optional second argument `projectRoot` controls path resolution
 * for the `docs` directory and the generated output. Defaults to
 * `process.cwd()`, which is the project root in most Vite/Webpack/Rspack
 * setups.
 */
import type { DocsConfig, SearchEntry, SidebarConfig } from "./types";
import { scanDocsDir } from "./scanner";
import { generateSidebar } from "./sidebar-generator";
import { buildSearchIndex } from "./search-index";
import { isAbsolute, resolve } from "node:path";
import { mkdirSync, writeFileSync } from "node:fs";

export function defineConfig(
  config: DocsConfig,
  projectRoot: string = process.cwd(),
): DocsConfig {
  generateRoutesFile(config, projectRoot);
  return config;
}

/**
 * Generate a physical routes module into `{projectRoot}/.lark-docs/generated/`.
 *
 * This file is regenerated each time the config is loaded (dev or build).
 * It imports all .md files (compiled by the bundler plugin), registers each
 * as a View class, and exports the route map + site data for boot.ts.
 *
 * Written to `.lark-docs/` (a dot directory at project root, similar to
 * `.vitepress/` or `.docusaurus/`) so it can be gitignored and inspected
 * directly. Consumers import it via a Vite resolve alias `@lark-docs/generated`.
 */
function generateRoutesFile(config: DocsConfig, projectRoot: string): void {
  const docsDir = isAbsolute(config.docs)
    ? config.docs
    : resolve(projectRoot, config.docs);

  const routes = scanDocsDir(docsDir, config.baseUrl);

  // Build sidebar
  const sidebar: Record<string, SidebarConfig> = {};
  if (config.sidebar) {
    for (const [prefix, sidebarConfig] of Object.entries(config.sidebar)) {
      if (sidebarConfig === "auto") {
        sidebar[prefix] = generateSidebar(routes, prefix, config.baseUrl);
      } else {
        sidebar[prefix] = sidebarConfig;
      }
    }
  }

  // Build search index (skip when provider is "none")
  const searchIndex: SearchEntry[] =
    config.search?.provider === "none" ? [] : buildSearchIndex(routes);

  const generatedDir = resolve(projectRoot, ".lark-docs/generated");

  // Generate dynamic-import loaders: route path -> () => import(filePath).
  // Each .md is compiled by the bundler plugin (larkDocsPlugin) into a module
  // exporting { pageData, contentHtml }. The layout view calls loadContent()
  // on navigation to fetch the matching page.
  const loaderEntries = routes
    .map(
      (r) =>
        `// @ts-ignore
      ${JSON.stringify(r.path)}: () => import(${JSON.stringify(r.filePath)}),`,
    )
    .join("\n");

  // Route map: every docs path maps to the single layout view.
  // The layout view stays mounted across navigation (viewId unchanged),
  // and observeLocation triggers an async render that loads fresh content.
  const routeMap: Record<string, string> = {};
  for (const route of routes) {
    routeMap[route.path] = "theme/docs-layout";
  }

  // Compose runtime docsConfig (includes build-time searchIndex,
  // which is not part of the user-facing DocsConfig type)
  const runtimeConfig = {
    title: config.title,
    description: config.description || "",
    lang: config.lang || "en-US",
    nav: config.nav || [],
    sidebar,
    searchIndex,
  };

  const fileContent = `// @ts-ignore
// Auto-generated by defineConfig() — DO NOT EDIT!!!
// Generated at: ${new Date().toISOString()}

const loaders: Record<string, () => Promise<any>> = {
${loaderEntries}
};

/**
 * Load a docs page's content module by route path.
 * Returns null for unknown paths so the layout can render a not-found state.
 */
export async function loadContent(
  path: string,
): Promise<{ pageData: unknown; contentHtml: string } | null> {
  const loader = loaders[path];
  if (!loader) return null;
  const mod = await loader();
  return { pageData: mod.pageData, contentHtml: mod.contentHtml };
}

export const routes: Record<string, string> = ${JSON.stringify(routeMap, null, 2)};

export const docsConfig = ${JSON.stringify(runtimeConfig, null, 2)};
`;

  // Write generated module to .lark-docs/generated/
  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(resolve(generatedDir, "index.ts"), fileContent, "utf-8");
}
