/**
 * Type-safe configuration helper with automatic route generation.
 *
 * Scans the docs directory, generates sidebar/search index, and writes
 * a routes module to `node_modules/@lark.js/docs/generated/` so that
 * `boot.ts` can import routes and site data with a bare module name.
 *
 * Usage:
 * ```ts
 * import { defineConfig } from "@lark.js/docs";
 *
 * export default defineConfig({
 *   docs: "docs",
 *   baseUrl: "/docs/",
 *   title: "My Library",
 * });
 * ```
 *
 * The optional second argument `projectRoot` controls path resolution
 * for the `docs` directory and the generated output. Defaults to
 * `process.cwd()`, which is the project root in most Vite/Webpack/Rspack
 * setups.
 */
import type { DocsConfig, SidebarConfig } from "./types";
import { scanDocsDir } from "./scanner";
import { generateRouteMap } from "./route-map";
import { generateSidebar } from "./sidebar-generator";
import { buildSearchIndex } from "./search-index";
import path from "node:path";
import fs from "node:fs";

export function defineConfig(
  config: DocsConfig,
  projectRoot: string = process.cwd(),
): DocsConfig {
  generateRoutesFile(config, projectRoot);
  return config;
}

/**
 * Generate a physical routes module into `{projectRoot}/node_modules/@lark.js/docs/generated/`.
 *
 * This file is regenerated each time the config is loaded (dev or build).
 * It imports all .md files (compiled by the bundler plugin), registers each
 * as a View class, and exports the route map + site data for boot.ts.
 *
 * Written to `node_modules` so it can be imported with the bare module name
 * `@lark.js/docs/generated`, which TypeScript resolves via the nested
 * `package.json` — relative module names are not valid in ambient
 * `declare module` declarations.
 */
function generateRoutesFile(config: DocsConfig, projectRoot: string): void {
  const docsDir = path.isAbsolute(config.docs)
    ? config.docs
    : path.resolve(projectRoot, config.docs);

  const routes = scanDocsDir(docsDir, config.baseUrl);
  const routeMap = generateRouteMap(routes);

  // Build sidebar
  const sidebar: Record<string, SidebarConfig> = {};
  if (config.sidebar) {
    for (const [prefix, sidebarConfig] of Object.entries(config.sidebar)) {
      if (sidebarConfig === "auto") {
        sidebar[prefix] = generateSidebar(routes, prefix, config.baseUrl);
      } else {
        sidebar[prefix] = sidebarConfig;
      }
    }
  }

  // Build search index (skip when provider is "none")
  const searchIndex =
    config.search?.provider === "none" ? [] : buildSearchIndex(routes);

  // Generate import statements for each .md file.
  // Use absolute paths to avoid resolution issues from the node_modules location.
  const generatedDir = path.resolve(
    projectRoot,
    "node_modules/@lark.js/docs/generated",
  );
  const imports = routes
    .map(
      (r, i) =>
        `// @ts-ignore
      import view${i} from ${JSON.stringify(r.filePath)};`,
    )
    .join("\n");

  // Generate registerViewClass calls
  const registrations = routes
    .map((r, i) => `registerViewClass(${JSON.stringify(r.viewId)}, view${i});`)
    .join("\n");

  // Compose runtime docsConfig (includes build-time searchIndex,
  // which is not part of the user-facing DocsConfig type)
  const runtimeConfig = {
    title: config.title,
    description: config.description || "",
    lang: config.lang || "en-US",
    nav: config.nav || [],
    sidebar,
    searchIndex,
  };

  const fileContent = `// Auto-generated by defineConfig() — DO NOT EDIT!!!
// Generated at: ${new Date().toISOString()}

import { registerViewClass } from "@lark.js/mvc";

${imports}

${registrations}

export const routes: Record<string, string> = ${JSON.stringify(routeMap, null, 2)};

export const docsConfig = ${JSON.stringify(runtimeConfig, null, 2)};
`;

  // Write generated module to node_modules/@lark.js/docs/generated/
  fs.mkdirSync(generatedDir, { recursive: true });
  fs.writeFileSync(
    path.resolve(generatedDir, "index.ts"),
    fileContent,
    "utf-8",
  );

  // // Write package.json so Node/Vite can resolve the bare module name
  // fs.writeFileSync(
  //   path.resolve(generatedDir, "package.json"),
  //   JSON.stringify(
  //     { name: "@lark.js/docs/generated", type: "module", main: "index.ts" },
  //     null,
  //     2,
  //   ),
  //   "utf-8",
  // );
}
