/**
 * Vite configuration for lark-homepage documentation site.
 *
 * Routes are auto-generated by @lark.js/docs defineConfig() —
 * no manual generateRoutesFile() needed here.
 */
import { defineConfig, type Plugin, type PluginOption, type UserConfig } from "vite";
import { resolve } from "node:path";
import { larkDocsPlugin } from "@lark.js/docs/vite";
import { larkMvcPlugin7 } from "@lark.js/mvc/vite";
import tailwindcss from "@tailwindcss/vite";
import docsConfig from "./lark-docs.config";

const PKG_DIR = import.meta.dirname;

// === Mode router ===

export default defineConfig(() => {
  return docsSiteConfig();
});

// === Documentation site build ===

function docsSiteConfig(): UserConfig {
  return {
    root: resolve(PKG_DIR, "docs/app"),
    plugins: [
      larkDocsPlugin({ config: docsConfig }) as Plugin,
      larkMvcPlugin7({
        debug: true,
        useSwc: true,
      }) as Plugin,
      tailwindcss() as PluginOption,
    ],
    resolve: {
      alias: {
        "@lark.js/docs": resolve(PKG_DIR, "../lark-docs/src"),
      },
    },
    build: {
      outDir: resolve(PKG_DIR, "dist-docs"),
      emptyOutDir: true,
    },
    server: {
      port: 3300,
      open: true,
    },
  };
}
