/**
 * Vite configuration for lark-homepage documentation site.
 *
 * Routes are auto-generated by @lark.js/docs defineConfig() —
 * no manual generateRoutesFile() needed here.
 */
import { defineConfig, type PluginOption, type UserConfigFn } from "vite";
import { resolve } from "node:path";
import { larkDocsPlugin } from "@lark.js/docs/vite";
import tailwindcss from "@tailwindcss/vite";
import { VitePWA } from "vite-plugin-pwa";
import docsConfig from "./lark-docs.config";

const PKG_DIR = import.meta.dirname;

// === Mode router ===

export default defineConfig((({ mode, command }) => {
  const isDev = mode === "development" || command === "serve";
  return {
    /**
     * 'serve': during dev (`vite` command)
     * 'build': when building for production (`vite build` command)
     */
    base: isDev ? "/" : "/lark/",
    root: resolve(PKG_DIR, "app"),
    plugins: [
      larkDocsPlugin({
        config: docsConfig,
        virtualDom: false,
        debug: true,
      }) as PluginOption,
      tailwindcss() as PluginOption,
      VitePWA({
        registerType: "autoUpdate",
        includeAssets: [
          "favicon.svg",
          "favicon.ico",
          "apple-touch-icon-180x180.png",
        ],
        manifest: {
          name: "Lark Index",
          short_name: "Lark",
          description: "Chrome homepage",
          theme_color: "#ecfdf5",
          background_color: "#ecfdf5",
          display: "standalone",
          scope: isDev ? "/" : "/lark/",
          start_url: isDev ? "/" : "/lark/",
          icons: [
            {
              src: "pwa-64x64.png",
              sizes: "64x64",
              type: "image/png",
            },
            {
              src: "pwa-192x192.png",
              sizes: "192x192",
              type: "image/png",
            },
            {
              src: "pwa-512x512.png",
              sizes: "512x512",
              type: "image/png",
            },
            {
              src: "maskable-icon-512x512.png",
              sizes: "512x512",
              type: "image/png",
              purpose: "maskable",
            },
          ],
        },
        workbox: {
          globPatterns: ["**/*.{js,css,html,svg,png,woff2}"],
          runtimeCaching: [
            {
              urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
              handler: "CacheFirst",
              options: {
                cacheName: "google-fonts-cache",
                expiration: {
                  maxEntries: 10,
                  maxAgeSeconds: 60 * 60 * 24 * 365,
                },
                cacheableResponse: { statuses: [0, 200] },
              },
            },
            {
              urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
              handler: "CacheFirst",
              options: {
                cacheName: "gstatic-fonts-cache",
                expiration: {
                  maxEntries: 10,
                  maxAgeSeconds: 60 * 60 * 24 * 365,
                },
                cacheableResponse: { statuses: [0, 200] },
              },
            },
          ],
        },
      }) as PluginOption,
    ],
    resolve: {
      alias: {
        "@lark-docs/generated": resolve(PKG_DIR, ".lark-docs/generated"),
      },
    },
    build: {
      outDir: resolve(PKG_DIR, "dist"),
      emptyOutDir: true,
    },
    server: {
      port: 3300,
      open: true,
    },
  };
}) satisfies UserConfigFn);
