/**
 * Vite configuration for lark-homepage documentation site.
 *
 * Generates routes from docs/ directory at startup, then serves
 * the site via Vite dev server or builds it for production.
 */
import { defineConfig, Plugin, type PluginOption, type UserConfig } from "vite";
import { resolve } from "node:path";
import path from "node:path";
import fs from "node:fs";
import {
  larkDocsPlugin,
  scanDocsDir,
  generateRouteMap,
  generateSidebar,
  buildSearchIndex,
} from "@lark.js/docs/vite";
import type { DocsConfig, SidebarConfig } from "@lark.js/docs/vite";
import { larkMvcPlugin7 } from "@lark.js/mvc/vite";
import tailwindcss from "@tailwindcss/vite";
import docsConfig from "./lark-docs.config";

const PKG_DIR = import.meta.dirname;

// === Mode router ===

export default defineConfig(({ mode }) => {
  generateRoutesFile(docsConfig);
  return docsSiteConfig();
});

// === Documentation site build ===

function docsSiteConfig(): UserConfig {
  return {
    root: resolve(PKG_DIR, "docs/app"),
    plugins: [
      larkDocsPlugin({ config: docsConfig }) as Plugin,
      larkMvcPlugin7({
        debug: true,
        useSwc: true,
      }) as Plugin,
      tailwindcss() as PluginOption,
    ],
    // resolve: {
    //   alias: {
    //     "@lark.js/docs": resolve(PKG_DIR, "../lark-docs/src"),
    //   },
    // },
    build: {
      outDir: resolve(PKG_DIR, "dist-docs"),
      emptyOutDir: true,
    },
    server: {
      port: 3300,
      open: true,
    },
  };
}

// === Routes file generator ===

function generateRoutesFile(config: DocsConfig): void {
  const docsDir = path.isAbsolute(config.docs)
    ? config.docs
    : resolve(PKG_DIR, config.docs);

  const routes = scanDocsDir(docsDir, config.baseUrl);
  const routeMap = generateRouteMap(routes);

  // Build sidebar
  const sidebar: Record<string, SidebarConfig> = {};
  if (config.sidebar) {
    for (const [prefix, sidebarConfig] of Object.entries(config.sidebar)) {
      if (sidebarConfig === "auto") {
        sidebar[prefix] = generateSidebar(routes, prefix, config.baseUrl);
      } else {
        sidebar[prefix] = sidebarConfig;
      }
    }
  }

  // Build search index
  const searchIndex =
    config.search?.provider === "none" ? [] : buildSearchIndex(routes);

  // Generate import statements for each .md file.
  const generatedDir = resolve(PKG_DIR, "node_modules/@lark.js/docs/generated");
  const imports = routes
    .map((r, i) => {
      return `// @ts-ignore
      import view${i} from ${JSON.stringify(r.filePath)};`;
    })
    .join("\n");

  // Generate registerViewClass calls
  const registrations = routes
    .map((r, i) => `registerViewClass(${JSON.stringify(r.viewId)}, view${i});`)
    .join("\n");

  // Compose docsConfig
  const configData = {
    title: config.title,
    description: config.description || "",
    lang: config.lang || "en-US",
    nav: config.nav || [],
    sidebar,
    searchIndex,
  };

  const fileContent = `// Auto-generated by vite.config.ts — DO NOT EDIT!!!
// Generated at: ${new Date().toISOString()}

import { registerViewClass } from "@lark.js/mvc";

${imports}

${registrations}

export const routes: Record<string, string> = ${JSON.stringify(routeMap, null, 2)};

export const docsConfig = ${JSON.stringify(configData, null, 2)};
`;

  // Write generated module to node_modules/@lark.js/docs/generated/
  fs.mkdirSync(generatedDir, { recursive: true });
  fs.writeFileSync(resolve(generatedDir, "index.ts"), fileContent, "utf-8");

  // Write package.json so Node/Vite can resolve the bare module name
  fs.writeFileSync(
    resolve(generatedDir, "package.json"),
    JSON.stringify(
      { name: "@lark.js/docs/generated", type: "module", main: "index.ts" },
      null,
      2,
    ),
    "utf-8",
  );
}
