import { Framework, View, State, registerViewClass } from "@lark.js/mvc";
import type { FrameworkConfig } from "@lark.js/mvc";

// Auto-generated by defineConfig()
import { routes, docsConfig, loadContent } from "@lark-docs/generated";

// Theme view factories + templates
import {
  createDocsLayoutView,
  createSidebarView,
  createTocView,
  createSearchView,
} from "@lark.js/docs/theme";

import docLayout from "@lark.js/docs/theme/docs-layout.html";
import sidebar from "@lark.js/docs/theme/sidebar.html";
import toc from "@lark.js/docs/theme/toc.html";
import search from "@lark.js/docs/theme/search.html";
// CSS
import "./main.css";

// === Register theme views ===

registerViewClass("theme/docs-layout", createDocsLayoutView(View, docLayout));
registerViewClass("theme/sidebar", createSidebarView(View, sidebar));
registerViewClass("theme/toc", createTocView(View, toc));
registerViewClass("theme/search", createSearchView(View, search));

// === Inject site data + content loader into State ===

State.set({ docsConfig, loadContent });

// === Boot ===

const config: FrameworkConfig = {
  rootId: "app",
  routeMode: "history",
  defaultPath: "/docs/",
  // All /docs/* routes map to "theme/docs-layout" (see generated routes).
  // The layout stays mounted across navigation; observeLocation triggers
  // an async render that loads the matching .md content via loadContent.
  defaultView: "theme/docs-layout",
  routes,
  unmatchedView: "theme/docs-layout",
  error(e: Error) {
    console.error("[lark-homepage]", e);
  },
};

Framework.boot(config);
