import { Framework, View, State, registerThemeViews } from "@lark.js/docs";
import type { FrameworkConfig } from "@lark.js/docs";

// Auto-generated by defineConfig()
import {
  routes,
  docsConfig,
  loadContent,
  getSearchIndex,
} from "@lark-docs/generated";

// CSS
import "./main.css";

// === Register theme views ===

registerThemeViews(View);

// === Inject site data + content loader into State ===

State.set({ docsConfig, loadContent, getSearchIndex });

// === Boot ===

const config: FrameworkConfig = {
  rootId: "app",
  routeMode: "history",
  defaultPath: "/lark/",
  // All /docs/* routes map to "theme/docs-layout" (see generated routes).
  // The layout stays mounted across navigation; observeLocation triggers
  // an async render that loads the matching .md content via loadContent.
  defaultView: "theme/docs-layout",
  routes,
  unmatchedView: "theme/docs-layout",
  error(e: Error) {
    console.error("[lark-homepage]", e);
  },
};

Framework.boot(config);
