import { Framework, View, State, registerViewClass } from "@lark.js/mvc";
import type { FrameworkConfig } from "@lark.js/mvc";

// Auto-generated by defineConfig()
import { routes, docsConfig } from "@lark-docs/generated";

// Theme view factories + templates
import {
  createDocsLayoutView,
  createSidebarView,
  createContentView,
  createTocView,
  createSearchView,
} from "@lark.js/docs/theme";

import docLayout from "@lark.js/docs/theme/docs-layout.html";
import sidebar from "@lark.js/docs/theme/sidebar.html";
import content from "@lark.js/docs/theme/content.html";
import toc from "@lark.js/docs/theme/toc.html";
import search from "@lark.js/docs/theme/search.html";
// CSS
import "./main.css";

// === Register theme views ===

registerViewClass("theme/docs-layout", createDocsLayoutView(View, docLayout));
registerViewClass("theme/sidebar", createSidebarView(View, sidebar));
registerViewClass("theme/content", createContentView(View, content));
registerViewClass("theme/toc", createTocView(View, toc));
registerViewClass("theme/search", createSearchView(View, search));

// === Inject site data into State ===

State.set({ docsConfig });

// === Boot ===

const config: FrameworkConfig = {
  rootId: "app",
  routeMode: "history",
  defaultPath: "/docs/",
  defaultView: "index",
  routes,
  unmatchedView: "index",
  error(e: Error) {
    console.error("[lark-homepage]", e);
  },
};

Framework.boot(config);
