/**
 * Documentation site boot entry.
 *
 * Imports the auto-generated routes module (produced by vite.config.ts
 * at startup) which registers all .md views and exports the route map
 * and site data.
 *
 * Then registers theme views, injects site data into State,
 * and boots the lark-mvc Framework.
 */
import { Framework, View, State, registerViewClass } from "@lark.js/mvc";
import type { FrameworkConfig } from "@lark.js/mvc";

// Auto-generated by vite.config.ts — registers docs views + exports routes/docsConfig
import { routes, docsConfig } from "../../node_modules/@lark.js/docs/generated";

// Theme view factories + templates
import {
  createDocsLayoutView,
  createSidebarView,
  createContentView,
  createTocView,
  createSearchView,
} from "@lark.js/docs/theme";

import docLayoutTemplate from "@lark.js/docs/theme/docs-layout.html";
import sidebarTemplate from "@lark.js/docs/theme/sidebar.html";
import contentTemplate from "@lark.js/docs/theme/content.html";
import tocTemplate from "@lark.js/docs/theme/toc.html";
import searchTemplate from "@lark.js/docs/theme/search.html";

// CSS (Tailwind + DaisyUI)
import "./main.css";

// === Register theme views ===

registerViewClass(
  "theme/docs-layout",
  createDocsLayoutView(View, docLayoutTemplate),
);
registerViewClass("theme/sidebar", createSidebarView(View, sidebarTemplate));
registerViewClass("theme/content", createContentView(View, contentTemplate));
registerViewClass("theme/toc", createTocView(View, tocTemplate));
registerViewClass("theme/search", createSearchView(View, searchTemplate));

// === Inject site data into State (cross-view access) ===

State.set({ docsConfig });

// === Boot ===

const config: FrameworkConfig = {
  rootId: "app",
  routeMode: "history",
  defaultPath: "/docs/",
  defaultView: "index",
  routes,
  unmatchedView: "index",
  error(e: Error) {
    console.error("[@lark.js/docs]", e);
  },
};

Framework.boot(config);
