/**
 * Documentation site boot entry.
 *
 * Imports the auto-generated routes module (produced by vite.config.ts
 * at startup) which exports the route map, site data, and a loadContent()
 * helper for dynamic .md content loading.
 *
 * Registers theme views, injects site data + loadContent into State,
 * and boots the lark-mvc Framework with the layout view as the single
 * mounted root view for all /docs/* routes.
 */
import { Framework, View, State } from "@lark.js/mvc";
import type { FrameworkConfig } from "@lark.js/mvc";

// Auto-generated by defineConfig() — exports routes + docsConfig + loadContent
import {
  routes,
  docsConfig,
  loadContent,
  getSearchIndex,
} from "@lark-docs/generated";

// Theme views (layout, sidebar, toc, search) — registered in one call.
// The framework imports and compiles the .html templates internally.
import { registerThemeViews } from "@lark.js/docs/theme";

// CSS (TailwindCSS + DaisyUI)
import "./main.css";

// === Register theme views ===

registerThemeViews(View);

// === Inject site data + content loader into State (cross-view access) ===

State.set({ docsConfig, loadContent, getSearchIndex });

// === Boot ===

const config: FrameworkConfig = {
  rootId: "app",
  routeMode: "history",
  defaultPath: "/docs/",
  // All /docs/* routes map to "theme/docs-layout" (see generated routes).
  // The layout stays mounted across navigation; observeLocation triggers
  // an async render that loads the matching .md content via loadContent.
  defaultView: "theme/docs-layout",
  routes,
  unmatchedView: "theme/docs-layout",
  error(e: Error) {
    console.error("[@lark.js/docs]", e);
  },
};

Framework.boot(config);
