/**
 * Markdown-to-lark-mvc-View compiler.
 *
 * Transforms a .md source string into a JS module string that exports
 * a lark-mvc View class. The compiled module is consumed at runtime
 * by the lark-mvc framework.
 *
 * Pipeline:
 * 1. Extract YAML frontmatter (js-yaml)
 * 2. Initialize Shiki highlighter (if configured)
 * 3. Parse markdown body to token stream (markdown-it + plugins)
 * 4. Render tokens to HTML string (with syntax-highlighted code blocks)
 * 5. Extract page metadata (title, headings)
 * 6. Wrap HTML in a JS module exporting pageData + template
 */
import { extractFrontmatter } from "../markdown/frontmatter";
import { createParser } from "../markdown/parser";
import { renderToLarkTemplate } from "../markdown/renderer";
import { getHighlighter, highlightCode } from "../markdown/highlighter";
import type { CompileMarkdownOptions } from "../types";
import { deriveTitleFromPath } from "../utils/derive-title";
import {
  extractFirstHeading,
  extractHeadings,
} from "../utils/heading-extraction";

/**
 * Compile a .md file source into a JS module string.
 *
 * The output module exports:
 * - `default`: a lark-mvc View-compatible object { pageData, template }
 * - `pageData`: static page metadata (title, description, headings)
 *
 * This function is async because Shiki highlighter initialization
 * requires loading WASM and TextMate grammars on first call.
 * The highlighter is cached as a singleton, so subsequent calls
 * resolve instantly.
 */
export async function compileMarkdown(
  source: string,
  options: CompileMarkdownOptions,
): Promise<string> {
  // 1. Extract frontmatter
  const { data: frontmatter, content } = extractFrontmatter(source);

  // 2. Create parser with user config
  const md = createParser(options.config.markdown);

  // 3. Initialize Shiki highlighter if configured
  if (options.config.highlight) {
    const hl = await getHighlighter(
      options.config.highlight.theme,
      options.config.highlight.languages,
    );
    const theme = options.config.highlight.theme;
    md.options.highlight = (code: string, lang: string) => {
      return highlightCode(hl, code, lang, theme);
    };
  }

  // 4. Parse and render to HTML
  const tokens = md.parse(content, {});
  const htmlBody = renderToLarkTemplate(tokens, md);

  // 5. Build page metadata
  const docsPrefix = options.config.docs.replace(/\/+$/, "") + "/";
  const relativeFilePath = options.filePath.startsWith(docsPrefix)
    ? options.filePath.slice(docsPrefix.length)
    : options.filePath;

  const title =
    (frontmatter["title"] as string) ||
    extractFirstHeading(content) ||
    deriveTitleFromPath(relativeFilePath);

  const headings = extractHeadings(content);

  const pageData = {
    title,
    description: (frontmatter["description"] as string) || "",
    sidebarPosition: frontmatter["sidebar_position"] as number | undefined,
    sidebarLabel: (frontmatter["sidebar_label"] as string) || undefined,
    sidebarGroup: (frontmatter["sidebar_group"] as string) || undefined,
    draft: (frontmatter["draft"] as boolean) || undefined,
    headings,
    relativePath: relativeFilePath,
  };

  // 6. Generate JS module
  return generateModule(htmlBody, pageData, options);
}

function generateModule(
  htmlBody: string,
  pageData: Record<string, unknown>,
  options: CompileMarkdownOptions,
): string {
  const pageDataJson = JSON.stringify(pageData, null, 2);

  // Escape the HTML for embedding in a JS template literal.
  // We need to escape backticks and dollar-brace sequences.
  const escapedHtml = htmlBody
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  return `// Generated by @lark.js/doc
// Source: ${options.filePath}

export const pageData = ${pageDataJson};

export default {
  pageData,
  template: function(data, viewId, refData) {
    return \`${escapedHtml}\`;
  },
};
`;
}
