name: Deploy https://hangtiancheng.github.io/lark homepage

on:
  push:
    branches: [main]
    # paths:
    #   - packages/lark-docs/**
    #   - .github/workflows/deploy.yml

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    if: "${{ github.event_name == 'workflow_dispatch' || github.event.head_commit.message == 'ci: Deploy homepage' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build lark-mvc
        run: pnpm --filter @lark.js/mvc build
      - name: Build lark-docs
        run: pnpm --filter @lark.js/docs build
      - name: Pull docs
        run: pnpm --filter @lark.js/docs git:pull
      - name: Build docs
        run: pnpm --filter @lark.js/docs build:docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/lark-docs/dist-docs

  deploy:
    if: "${{ github.event_name == 'workflow_dispatch' || github.event.head_commit.message == 'ci: Deploy homepage' }}"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
